version: '3.8'

services:
  postgres:
    image: postgres:alpine3.18
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/000_init.sql:/docker-entrypoint-initdb.d/000_init.sql

  userhub-service:
    build: ./../../userhub-service
    restart: always
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: curl --fail http://localhost:8080/actuator/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 2
      start_period: 35s
    ports:
      - '8081:8080'

volumes:
  db-data: