version: '3.8'

services:
  postgres:
    image: postgres:alpine3.18
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=userhub-service-db-dev
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local